swagger: "2.0"
info:
  title: WordBurglar API
  description: WordBurglar API
  version: 1.0.0

schemes:
  - https

paths:
  /session:
    get:
      summary: Get a new session
      operationId: getNewSession
      responses:
        "200":
          description: Successful response
      x-google-backend:
        address: https://FUNCTIONS_URI/get-session

    options:
      summary: Preflight support for getNewSession
      operationId: getNewSession_PF
      responses:
        "204":
          description: No content
      x-google-backend:
        address: https://FUNCTIONS_URI/get-session

  /session/{sessionID}:
    get:
      summary: Get session by ID
      operationId: getSessionByID
      parameters:
        - name: sessionID
          in: path
          required: true
          type: string
          description: Optional session ID
      responses:
        "200":
          description: Successful response
      x-google-backend:
        address: https://FUNCTIONS_URI/get-session
        pathTranslation: APPEND_PATH_TO_ADDRESS

    options:
      summary: Preflight support for getSessionByID
      operationId: getSessionByID_PF
      parameters:
        - name: sessionID
          in: path
          required: true
          type: string
          description: Optional session ID
      responses:
        "204":
          description: No content
      x-google-backend:
        address: https://FUNCTIONS_URI/get-session
        pathTranslation: APPEND_PATH_TO_ADDRESS

  /next-word:
    post:
      summary: Get the next word
      operationId: getNextWord
      consumes:
        - application/json
      responses:
        "200":
          description: Successful response
      x-google-backend:
        address: https://FUNCTIONS_URI/get-next-word

    options:
      summary: Preflight support for getNextWord
      operationId: getNextWord_PF
      consumes:
        - application/json
      responses:
        "204":
          description: No content
      x-google-backend:
        address: https://FUNCTIONS_URI/get-next-word
