name: Deploy API Gateway

on:
  push:
    paths:
      - config/api-gateway.yaml
      - .github/workflows/api-gateway-pipeline.yaml
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_DEPLOYMENT_KEY }}

      - name: Setup GCloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Set project
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_NAME }}

      - name: Upload and deploy API config
        run: |
          cd config

          TIMESTAMP=$(date +%s)
          CONFIG_NAME="api-config-$TIMESTAMP"

          gcloud api-gateway api-configs create $CONFIG_NAME \
            --api=${{ secrets.API_NAME }} \
            --openapi-spec=api-gateway.yaml \
            --project=${{ secrets.GCP_PROJECT_NAME }}

          gcloud api-gateway gateways update ${{ secrets.API_GATEWAY_NAME }} \
            --api=${{ secrets.API_NAME }} \
            --api-config=$CONFIG_NAME \
            --location=${{ secrets.GCP_REGION }}