name: Deploy CleanupTimer Function

on:
  push:
    paths:
      - ".github/workflows/cleanup-timer-pipeline.yaml"
      - "gcp-functions/cleanup-timer/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_DEPLOYMENT_KEY }}

    - name: Setup GCloud CLI
      uses: google-github-actions/setup-gcloud@v2

    - name: Deploy Cloud Function
      run: |
        cd gcp-functions/cleanup-timer
        chmod 700 deploy.sh
        ./deploy.sh
        