name: Deploy to App Engine

on:
  push:
    paths:
      - ".github/workflows/common-solution-search-pipeline.yaml"
      - "gcp-functions/common-solution-search/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_DEPLOYMENT_KEY }}

    - name: Deploy serverless function
      uses: google-github-actions/deploy-cloud-functions@v2
      with:
        name: common-solution-search
        runtime: go123
        region: us-east4
        entry_point: CommonSolutionSearch
        source_dir: gcp-functions/common-solution-search
        project_id: ${{ secrets.GCP_PROJECT_ID }}