name: Deploy CommonSolutionSearch Function

on:
  push:
    paths:
      - ".github/workflows/common-solution-search-pipeline.yaml"
      - "gcp-functions/common-solution-search/**"
      - "gcp-functions/golang-models/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy models to function directory
      run: |
        cd gcp-functions/common-solution-search
        cp ../golang-models/*.go .

    - name: Build Solution Search Index
      run: |
        cd gcp-functions/compute-next-word
        npm run build-cs-idx
        cp ./common-solutions.json ../common-solution-search/common-solutions.json

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_DEPLOYMENT_KEY }}

    - name: Setup GCloud CLI
      uses: google-github-actions/setup-gcloud@v2

    - name: Deploy Cloud Function
      run: |
        cd gcp-functions/common-solution-search
        chmod 700 deploy.sh
        ./deploy.sh
        