name: Deploy GetNextWord Function

on:
  push:
    paths:
      - ".github/workflows/get-next-word-pipeline.yaml"
      - "gcp-functions/get-next-word/**"
      - "gcp-functions/golang-models/**"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy models to function directory
      run: |
        cd gcp-functions/get-next-word
        cp ../golang-models/*.go .

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_DEPLOYMENT_KEY }}

    - name: Setup GCloud CLI
      uses: google-github-actions/setup-gcloud@v2

    - name: Set environment variables
      run: |
        echo "GCP_PROJECT_NAME=${{ secrets.GCP_PROJECT_NAME }}" >> $GITHUB_ENV
        echo "BASE_URI=${{ secrets.BASE_URI }}" >> $GITHUB_ENV

    - name: Deploy Cloud Function
      run: |
        cd gcp-functions/get-next-word
        chmod 700 deploy.sh
        ./deploy.sh
        